M48
; DRILL file {KiCad (6.0.1)} date za 05 feb 2022 13:32:04 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-05T13:32:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X6.2685Y-1.4713
X6.2685Y-1.6287
T2
X5.3Y-2.3465
X5.3Y-2.6417
T0
M30
