M48
; DRILL file {KiCad 7.0.1} date vr 28 apr 2023 09:36:02 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-28T09:36:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.75Y-2.05
X5.75Y-2.15
X5.75Y-2.25
X5.8Y-1.675
T2
X4.775Y-1.95
X5.9Y-1.7
X5.9Y-1.8
X5.9Y-1.9
X5.9Y-2.0
X5.9Y-2.1
X5.9Y-2.2
X6.0Y-1.7
X6.0Y-1.8
X6.0Y-1.9
X6.0Y-2.0
X6.0Y-2.1
X6.0Y-2.2
T0
M30
