M48
; DRILL file {KiCad (6.0.1)} date wo 02 feb 2022 16:31:28 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-02T16:31:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.163Y-5.0394
X3.2181Y-3.4331
X4.2024Y-3.4331
X4.2575Y-5.0394
T0
M30
